import { Book } from "./models/book.models";

export const OLD_TESTAMENT_BOOKS_LIST: Book[] = [
  {
    name: "Genesis",
    name_fr: "Genèse",
    slug: "genesis",
    slug2: "GEN",
    chaptersCount: 50,
  },
  {
    name: "Exodus",
    name_fr: "Exode",
    slug: "exodus",
    slug2: "EXO",
    chaptersCount: 40,
  },
  {
    name: "Leviticus",
    name_fr: "Lévitique",
    slug: "leviticus",
    slug2: "LEV",
    chaptersCount: 27,
  },
  {
    name: "Numbers",
    name_fr: "Nombres",
    slug: "numbers",
    slug2: "NUM",
    chaptersCount: 36,
  },
  {
    name: "Deuteronomy",
    name_fr: "Deutéronome",
    slug: "deuteronomy",
    slug2: "DEU",
    chaptersCount: 34,
  },
  {
    name: "Joshua",
    name_fr: "Josué",
    slug: "joshua",
    slug2: "JOS",
    chaptersCount: 24,
  },
  {
    name: "Judges",
    name_fr: "Juges",
    slug: "judges",
    slug2: "JDG",
    chaptersCount: 21,
  },
  {
    name: "Ruth",
    name_fr: "Ruth",
    slug: "ruth",
    slug2: "RUT",
    chaptersCount: 4,
  },
  {
    name: "1 Samuel",
    name_fr: "1 Samuel",
    slug: "1samuel",
    slug2: "1SA",
    chaptersCount: 31,
  },
  {
    name: "2 Samuel",
    name_fr: "2 Samuel",
    slug: "2samuel",
    slug2: "2SA",
    chaptersCount: 24,
  },
  {
    name: "1 Kings",
    name_fr: "1 Rois",
    slug: "1kings",
    slug2: "1KI",
    chaptersCount: 22,
  },
  {
    name: "2 Kings",
    name_fr: "2 Rois",
    slug: "2kings",
    slug2: "2KI",
    chaptersCount: 25,
  },
  {
    name: "1 Chronicles",
    name_fr: "1 Chroniques",
    slug: "1chronicles",
    slug2: "1CH",
    chaptersCount: 29,
  },
  {
    name: "2 Chronicles",
    name_fr: "2 Chroniques",
    slug: "2chronicles",
    slug2: "2CH",
    chaptersCount: 36,
  },
  {
    name: "Ezra",
    name_fr: "Esdras",
    slug: "ezra",
    slug2: "EZR",
    chaptersCount: 10,
  },
  {
    name: "Nehemiah",
    name_fr: "Néhémie",
    slug: "nehemiah",
    slug2: "NEH",
    chaptersCount: 13,
  },
  {
    name: "Esther",
    name_fr: "Esther",
    slug: "esther",
    slug2: "EST",
    chaptersCount: 10,
  },
  { name: "Job", name_fr: "Job", slug: "job", slug2: "JOB", chaptersCount: 42 },
  {
    name: "Psalms",
    name_fr: "Psaumes",
    slug: "psalms",
    slug2: "PSA",
    chaptersCount: 150,
  },
  {
    name: "Proverbs",
    name_fr: "Proverbes",
    slug: "proverbs",
    slug2: "PRO",
    chaptersCount: 31,
  },
  {
    name: "Ecclesiastes",
    name_fr: "Ecclésiaste",
    slug: "ecclesiastes",
    slug2: "ECC",
    chaptersCount: 12,
  },
  {
    name: "Song of Solomon",
    name_fr: "Cantique des Cantiques",
    slug: "songofsolomon",
    slug2: "SNG",
    chaptersCount: 8,
  },
  {
    name: "Isaiah",
    name_fr: "Ésaïe",
    slug: "isaiah",
    slug2: "ISA",
    chaptersCount: 66,
  },
  {
    name: "Jeremiah",
    name_fr: "Jérémie",
    slug: "jeremiah",
    slug2: "JER",
    chaptersCount: 52,
  },
  {
    name: "Lamentations",
    name_fr: "Lamentations",
    slug: "lamentations",
    slug2: "LAM",
    chaptersCount: 5,
  },
  {
    name: "Ezekiel",
    name_fr: "Ézéchiel",
    slug: "ezekiel",
    slug2: "EZK",
    chaptersCount: 48,
  },
  {
    name: "Daniel",
    name_fr: "Daniel",
    slug: "daniel",
    slug2: "DAN",
    chaptersCount: 12,
  },
  {
    name: "Hosea",
    name_fr: "Osée",
    slug: "hosea",
    slug2: "HOS",
    chaptersCount: 14,
  },
  {
    name: "Joel",
    name_fr: "Joël",
    slug: "joel",
    slug2: "JOL",
    chaptersCount: 3,
  },
  {
    name: "Amos",
    name_fr: "Amos",
    slug: "amos",
    slug2: "AMO",
    chaptersCount: 9,
  },
  {
    name: "Obadiah",
    name_fr: "Abdias",
    slug: "obadiah",
    slug2: "OBA",
    chaptersCount: 1,
  },
  {
    name: "Jonah",
    name_fr: "Jonas",
    slug: "jonah",
    slug2: "JON",
    chaptersCount: 4,
  },
  {
    name: "Micah",
    name_fr: "Michée",
    slug: "micah",
    slug2: "MIC",
    chaptersCount: 7,
  },
  {
    name: "Nahum",
    name_fr: "Nahum",
    slug: "nahum",
    slug2: "NAM",
    chaptersCount: 3,
  },
  {
    name: "Habakkuk",
    name_fr: "Habacuc",
    slug: "habakkuk",
    slug2: "HAB",
    chaptersCount: 3,
  },
  {
    name: "Zephaniah",
    name_fr: "Sophonie",
    slug: "zephaniah",
    slug2: "ZEP",
    chaptersCount: 3,
  },
  {
    name: "Haggai",
    name_fr: "Aggée",
    slug: "haggai",
    slug2: "HAG",
    chaptersCount: 2,
  },
  {
    name: "Zechariah",
    name_fr: "Zacharie",
    slug: "zechariah",
    slug2: "ZEC",
    chaptersCount: 14,
  },
  {
    name: "Malachi",
    name_fr: "Malachie",
    slug: "malachi",
    slug2: "MAL",
    chaptersCount: 4,
  },
];

export const NEW_TESTAMENT_BOOKS_LIST: Book[] = [
  {
    name: "Matthew",
    name_fr: "Matthieu",
    slug: "matthew",
    slug2: "MAT",
    chaptersCount: 28,
  },
  {
    name: "Mark",
    name_fr: "Marc",
    slug: "mark",
    slug2: "MRK",
    chaptersCount: 16,
  },
  {
    name: "Luke",
    name_fr: "Luc",
    slug: "luke",
    slug2: "LUK",
    chaptersCount: 24,
  },
  {
    name: "John",
    name_fr: "Jean",
    slug: "john",
    slug2: "JHN",
    chaptersCount: 21,
  },
  {
    name: "Acts",
    name_fr: "Actes",
    slug: "acts",
    slug2: "ACT",
    chaptersCount: 28,
  },
  {
    name: "Romans",
    name_fr: "Romains",
    slug: "romans",
    slug2: "ROM",
    chaptersCount: 16,
  },
  {
    name: "1 Corinthians",
    name_fr: "1 Corinthiens",
    slug: "1corinthians",
    slug2: "1CO",
    chaptersCount: 16,
  },
  {
    name: "2 Corinthians",
    name_fr: "2 Corinthiens",
    slug: "2corinthians",
    slug2: "2CO",
    chaptersCount: 13,
  },
  {
    name: "Galatians",
    name_fr: "Galates",
    slug: "galatians",
    slug2: "GAL",
    chaptersCount: 6,
  },
  {
    name: "Ephesians",
    name_fr: "Éphésiens",
    slug: "ephesians",
    slug2: "EPH",
    chaptersCount: 6,
  },
  {
    name: "Philippians",
    name_fr: "Philippiens",
    slug: "philippians",
    slug2: "PHP",
    chaptersCount: 4,
  },
  {
    name: "Colossians",
    name_fr: "Colossiens",
    slug: "colossians",
    slug2: "COL",
    chaptersCount: 4,
  },
  {
    name: "1 Thessalonians",
    name_fr: "1 Thessaloniciens",
    slug: "1thessalonians",
    slug2: "1TH",
    chaptersCount: 5,
  },
  {
    name: "2 Thessalonians",
    name_fr: "2 Thessaloniciens",
    slug: "2thessalonians",
    slug2: "2TH",
    chaptersCount: 3,
  },
  {
    name: "1 Timothy",
    name_fr: "1 Timothée",
    slug: "1timothy",
    slug2: "1TI",
    chaptersCount: 6,
  },
  {
    name: "2 Timothy",
    name_fr: "2 Timothée",
    slug: "2timothy",
    slug2: "2TI",
    chaptersCount: 4,
  },
  {
    name: "Titus",
    name_fr: "Tite",
    slug: "titus",
    slug2: "TIT",
    chaptersCount: 3,
  },
  {
    name: "Philemon",
    name_fr: "Philémon",
    slug: "philemon",
    slug2: "PHM",
    chaptersCount: 1,
  },
  {
    name: "Hebrews",
    name_fr: "Hébreux",
    slug: "hebrews",
    slug2: "HEB",
    chaptersCount: 13,
  },
  {
    name: "James",
    name_fr: "Jacques",
    slug: "james",
    slug2: "JAS",
    chaptersCount: 5,
  },
  {
    name: "1 Peter",
    name_fr: "1 Pierre",
    slug: "1peter",
    slug2: "1PE",
    chaptersCount: 5,
  },
  {
    name: "2 Peter",
    name_fr: "2 Pierre",
    slug: "2peter",
    slug2: "2PE",
    chaptersCount: 3,
  },
  {
    name: "1 John",
    name_fr: "1 Jean",
    slug: "1john",
    slug2: "1JN",
    chaptersCount: 5,
  },
  {
    name: "2 John",
    name_fr: "2 Jean",
    slug: "2john",
    slug2: "2JN",
    chaptersCount: 1,
  },
  {
    name: "3 John",
    name_fr: "3 Jean",
    slug: "3john",
    slug2: "3JN",
    chaptersCount: 1,
  },
  {
    name: "Jude",
    name_fr: "Jude",
    slug: "jude",
    slug2: "JUD",
    chaptersCount: 1,
  },
  {
    name: "Revelation",
    name_fr: "Apocalypse",
    slug: "revelation",
    slug2: "REV",
    chaptersCount: 22,
  },
];

export const ALL_BIBLE_BOOKS = OLD_TESTAMENT_BOOKS_LIST.concat(
  NEW_TESTAMENT_BOOKS_LIST
);
