import { Book } from "./models/book.models";

export const OLD_TESTAMENT_BOOKS_LIST: Book[] = [
  { name: "Genesis", slug: "genesis", chaptersCount: 50, slug2: "GEN" },
  { name: "Exodus", slug: "exodus", chaptersCount: 40, slug2: "EXO" },
  { name: "Leviticus", slug: "leviticus", chaptersCount: 27, slug2: "LEV" },
  { name: "Numbers", slug: "numbers", chaptersCount: 36, slug2: "NUM" },
  {
    name: "Deuteronomy",
    slug: "deuteronomy",
    chaptersCount: 34,
    slug2: "DEU",
  },
  { name: "Joshua", slug: "joshua", chaptersCount: 24, slug2: "JOS" },
  { name: "Judges", slug: "judges", chaptersCount: 21, slug2: "JDG" },
  { name: "Ruth", slug: "ruth", chaptersCount: 4, slug2: "RUT" },
  { name: "1 Samuel", slug: "1samuel", chaptersCount: 31, slug2: "1SA" },
  { name: "2 Samuel", slug: "2samuel", chaptersCount: 24, slug2: "2SA" },
  { name: "1 Kings", slug: "1kings", chaptersCount: 22, slug2: "1KI" },
  { name: "2 Kings", slug: "2kings", chaptersCount: 25, slug2: "2KI" },
  {
    name: "1 Chronicles",
    slug: "1chronicles",
    chaptersCount: 29,
    slug2: "1CH",
  },
  {
    name: "2 Chronicles",
    slug: "2chronicles",
    chaptersCount: 36,
    slug2: "2CH",
  },
  { name: "Ezra", slug: "ezra", chaptersCount: 10, slug2: "EZR" },
  { name: "Nehemiah", slug: "nehemiah", chaptersCount: 13, slug2: "NEH" },
  { name: "Esther", slug: "esther", chaptersCount: 10, slug2: "EST" },
  { name: "Job", slug: "job", chaptersCount: 42, slug2: "JOB" },
  { name: "Psalms", slug: "psalms", chaptersCount: 150, slug2: "PSA" },
  { name: "Proverbs", slug: "proverbs", chaptersCount: 31, slug2: "PRO" },
  {
    name: "Ecclesiastes",
    slug: "ecclesiastes",
    chaptersCount: 12,
    slug2: "ECC",
  },
  {
    name: "Song of Solomon",
    slug: "songofsolomon",
    chaptersCount: 8,
    slug2: "SNG",
  },
  { name: "Isaiah", slug: "isaiah", chaptersCount: 66, slug2: "ISA" },
  { name: "Jeremiah", slug: "jeremiah", chaptersCount: 52, slug2: "JER" },
  {
    name: "Lamentations",
    slug: "lamentations",
    chaptersCount: 5,
    slug2: "LAM",
  },
  { name: "Ezekiel", slug: "ezekiel", chaptersCount: 48, slug2: "EZK" },
  { name: "Daniel", slug: "daniel", chaptersCount: 12, slug2: "DAN" },
  { name: "Hosea", slug: "hosea", chaptersCount: 14, slug2: "HOS" },
  { name: "Joel", slug: "joel", chaptersCount: 3, slug2: "JOL" },
  { name: "Amos", slug: "amos", chaptersCount: 9, slug2: "AMO" },
  { name: "Obadiah", slug: "obadiah", chaptersCount: 1, slug2: "OBA" },
  { name: "Jonah", slug: "jonah", chaptersCount: 4, slug2: "JON" },
  { name: "Micah", slug: "micah", chaptersCount: 7, slug2: "MIC" },
  { name: "Nahum", slug: "nahum", chaptersCount: 3, slug2: "NAM" },
  { name: "Habakkuk", slug: "habakkuk", chaptersCount: 3, slug2: "HAB" },
  { name: "Zephaniah", slug: "zephaniah", chaptersCount: 3, slug2: "ZEP" },
  { name: "Haggai", slug: "haggai", chaptersCount: 2, slug2: "HAG" },
  { name: "Zechariah", slug: "zechariah", chaptersCount: 14, slug2: "ZEC" },
  { name: "Malachi", slug: "malachi", chaptersCount: 4, slug2: "MAL" },
];

export const NEW_TESTAMENT_BOOKS_LIST: Book[] = [
  { name: "Matthew", slug: "matthew", chaptersCount: 28, slug2: "MAT" },
  { name: "Mark", slug: "mark", chaptersCount: 16, slug2: "MRK" },
  { name: "Luke", slug: "luke", chaptersCount: 24, slug2: "LUK" },
  { name: "John", slug: "john", chaptersCount: 21, slug2: "JHN" },
  { name: "Acts", slug: "acts", chaptersCount: 28, slug2: "ACT" },
  { name: "Romans", slug: "romans", chaptersCount: 16, slug2: "ROM" },
  {
    name: "1 Corinthians",
    slug: "1corinthians",
    chaptersCount: 16,
    slug2: "1CO",
  },
  {
    name: "2 Corinthians",
    slug: "2corinthians",
    chaptersCount: 13,
    slug2: "2CO",
  },
  { name: "Galatians", slug: "galatians", chaptersCount: 6, slug2: "GAL" },
  { name: "Ephesians", slug: "ephesians", chaptersCount: 6, slug2: "EPH" },
  { name: "Philippians", slug: "philippians", chaptersCount: 4, slug2: "PHP" },
  { name: "Colossians", slug: "colossians", chaptersCount: 4, slug2: "COL" },
];
